### PR TITLE
Adds AlmaLinux Support

### PR DESCRIPTION
**Pull request by JamuelStarkey**
Added AlamaLinux to the list of detectable distributions.

### CODE REVIEW

**Comment by stormi** [comment]
I suppose you made the script return "rhel" so that install.sh works but the proper fix would be to let install.sh know how to handle almalinux. This is something we should be able to contribute in the future once Citrix puts install.sh into this repository as they said they were going to do soon.

**Comment by JamuelStarkey** [comment]
@stormi I've updated the patch per your suggestion.  The distro is now set to almalinux.   install.sh now gracefully chokes on the distro type rather than having the sed error: 

```
Detected `AlmaLinux release 8.3 (Purple Manul)' (almalinux version 8).

Unable to install guest packages for distribution
AlmaLinux release 8.3 (Purple Manul) (almalinux).

Unknown Linux distribution `almalinux'.

You should manually install a version of
xe-guest-utilities which is suitable for your
distribution.

```

**Review by minli1 — APPROVED** [review]

**Review by xihuan-citrix — APPROVED** [review]

**Comment by stormi** [comment]
Nice that it was merged fast. A few minor comments though:
- There remain typos in comments ("Alama" instead of "Alma" in two places)
- It would have made for a cleaner and meaningful git history if the commits had been squashed together before the merge. 
- It would be nice to enable DCO checks on this repo (see https://github.com/apps/dco that is what the XAPI project uses)

**Comment by minli1** [comment]
Thanks for your reply.
1. Submit PR https://github.com/xenserver/xe-guest-utilities/pull/100 to fix the typo.
2. Yes, it should be squashed and will do in future PRs.
3. I have requested the DCO check to this repo, it may take time to be approved by the admin.

**Comment by JamuelStarkey** [comment]
I'll fix the typos and read up on DCO. Is there a way to squash directly from git hub?

On May 6, 2021, at 11:57 PM, Samuel VERSCHELDE ***@***.***> wrote:

﻿

Nice that it was merged fast. A few minor comments though:

  *   There remain typos in comments ("Alama" instead of "Alma" in two places)
  *   It would have made for a cleaner and meaningful git history if the commits had been squashed together before the merge.
  *   It would be nice to enable DCO checks on this repo (see https://github.com/apps/dco that is what the XAPI project uses)

**Comment by stormi** [comment]
The typos are being handled in PR #100 already.

To squash your commits (but it's too late for this PR since it was merged already), you need to use `git rebase -i [...]`. Github has a feature to allow the maintainer to squash the commits when they merge but it's better if it's done by the committer.

**Comment by JamuelStarkey** [comment]
Thank you for your patience.   DCO details noted.

On May 7, 2021, at 12:49 AM, Samuel VERSCHELDE ***@***.***> wrote:

﻿

The typos are being handled in PR #100<https://github.com/xenserver/xe-guest-utilities/pull/100> already.

To squash your commits (but it's too late for this PR since it was merged already), you need to use git rebase -i [...] and then force-push your branch. Github has a feature to allow the maintainer to squash the commits when they merge but it's better if it's done by the committer.

**Pull request merged**
