### PR TITLE
feat: Slackware support

### PR DESCRIPTION
**Pull request by mco-system**
Added Slackware support to xe-linux-distribution

### CODE REVIEW

**Comment by mco-system** [comment]
@minli1 Hi,  Here a link to a Xen-Orchestra screenshot showing a Slackware 15.0 Linux virtual machine running on XCP-ng with patched xe-linux-distribution.
https://i.imgur.com/LbPQtyQ.png

**Comment by mco-system** [comment]
Here the content of a typical  `/etc/slackware-version` file:
```shell
$  ssh slack-02.local.mcos.nc cat /etc/slackware-version
Slackware 15.0

**Review by minli1 — APPROVED** [review]

**Review by xihuan-citrix — APPROVED** [review]

**Comment by stormi** [comment]
There's no /etc/os-release in slackware that https://github.com/xenserver/xe-guest-utilities/pull/116 would have been able to automatically read?

**Comment by stormi** [comment]
IMO it would also have been good to add a test case in https://github.com/xenserver/xe-guest-utilities/tree/master/mk/testcases

**Comment by mco-system** [comment]
@stormi  Yes there is a  `/etc/os-release` file in Slackware Linux. I didn't realized that there was a `identify_os_release` function since this function is not yet present in XCP-NG.
I tested the `identify_os_release`  function over Slackware and it works as expected.

I suppose there is no more need for a specific Slackware test.

**Comment by stormi** [comment]
Indeed, `identify_os_release` is not included yet in any release from XCP-ng or Citrix Hypervisor, but backporting it is on my todo list.

**Comment by mco-system** [comment]
@stormi Done in [#122](https://github.com/xenserver/xe-guest-utilities/pull/122)
I finally removed the `identify_slackware()` function from `xe-linux-distribution` and added an `identify_os_release()` call to `xe-linux-distribution-test`.

Not sure thas is what you expected. You tell me :)

**Pull request merged**
