### PR TITLE
CP-16739: Make watch in status

### PR DESCRIPTION
**Pull request by cheng-z**
Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>

### CODE REVIEW

**Comment by cheng-z** [comment]
Hi @phusl 
Thanks for your comments.
Could you please help to look at the logger I add in xenstore.go again?
Thanks in advance.

**Comment by phusl** [comment]
offline Reviewed, LGTM. :+1:

**Comment by cheng-z** [comment]
Hi @robertbreker 
Could you please help to also review the code and see if we can merge the code or not?
Thanks.

**Comment by cheng-z** [comment]
@Zhengchai 
Could you please help to review the code and merge if possible?
Thanks.

**Comment by Zhengchai** [comment]
Merge it now for prototype testing. @robertbreker  could give comments later when come back :-).

**Comment by robertbreker** [comment]
+1 for watches :)

**Pull request merged**
