### PR TITLE
Trivial patches for xenstore-* tools packaging

### PR DESCRIPTION
**Pull request by cheese**

### CODE REVIEW

**Comment by TalonsLee** [comment]
the rpm spec is actually never used in our build system.
Please confirm it works.

The symbol link change looks good.

**Comment by cheese** [comment]
We use that specfile in our derived work. And the patch of specfile is insane.

**Comment by stormi** [comment]
This change looks good to me. Maybe it should get a review? The OP answered all questions.

**Review by minli1 — APPROVED** [review]

**Comment by stormi** [comment]
This change has one approval, maybe it could get another and be merged?

**Review by xihuan-citrix — APPROVED** [review]

**Pull request merged**
