### PR TITLE
Make xe-daemon generate less xenstore traffic

### PR DESCRIPTION
**Pull request by jjd27**
The first commit is an attempted bug-fix. Please review that this now restores the intended behaviour of the write-cache.

The second commit is a proposed optimisation. I personally don't see the need for the 2-minute timeout for the cache. But perhaps I am missing something, so please correct me if there's a reason we need this.

### CODE REVIEW

**Comment by jjd27** [comment]
Good point! No, they are not preserved. Perhaps the best solution is for the guest-agent to watch `domid` and to flush the cache whenever it changes.

**Comment by djs55** [comment]
Note that domid doesn't always change on migration. Have a look at CA-30811 and this line of code:

https://github.com/xapi-project/xenopsd/blob/b15a11f29abf7671f000bcf0cbd03e4d15e97998/xc/domain.ml#L262

The idea was to allow the guest agent to watch this id which is guaranteed to be different on every domain create.

**Comment by jjd27** [comment]
Glad to see that's already a solved problem. Thanks, djs55!

**Comment by djs55** [comment]
I claim that this refutes the idea that embedding unreadable ticket
identifiers in the code makes it harder for external people to contribute--
in this case it made it easier ;-)

On Tue, Mar 15, 2016 at 2:02 PM, Jonathan Davies <notifications@github.com>
wrote:

> Glad to see that's already a solved problem. Thanks, djs55!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/xenserver/xe-guest-utilities/pull/12#issuecomment-196834769
>



-- 
Dave Scott

**Comment by jjd27** [comment]
Happily, the original code already does this -- c.f. https://github.com/jjd27/xe-guest-utilities/blob/29a6d76f70db7/xe-daemon/xe-daemon.go#L87-L98 -- it flushes the cache when it notices the `unique-domain-id` has changed since the previous iteration. (This means we might wait up to 1 minute, which isn't quite as good as watching that path and reacting immediately, but it is at least as responsive as the previous behaviour in which the cache was flushed every 2 minutes.)

**Comment by phusl** [comment]
Great improvements! I think we'd merge this PR immediately :+1:  :+1:  :+1: 
@Zhengchai @robertbreker

**Comment by Zhengchai** [comment]
Merge now.

**Pull request merged**
