### PR TITLE
Fix indentation: remove tabs

### PR DESCRIPTION
**Pull request by stormi**
There was a mix of tabs and spaces so I replaced the tabs with spaces (8
spaces for one tab, except when there were already spaces inside the
tab space).

Signed-off-by: Samuel Verschelde <stormi-xcp@ylix.fr>

### CODE REVIEW

**Review by minli1 — DISMISSED** [review]

**Comment by xihuan-citrix** [comment]
Could you paste the basic test results for your modification on a specific guest?

**Review by xihuan-citrix — DISMISSED** [review]

**Comment by stormi** [comment]
I was not sure what you were asking exactly, so I ran the old `xe-linux-distribution-test` script after replacing `/sbin/xe-linux-distribution`.

```
[root@localhost ~]# cp xe-linux-distribution /sbin/xe-linux-distribution 
cp : voulez-vous écraser '/sbin/xe-linux-distribution' ? y
[root@localhost ~]# ./xe-linux-distribution-test 
PASSED: testcases/debian-sid: debian   Debian lenny/sid correctly detected
PASSED: testcases/rhel-3u6: rhel 3 6 Red Hat Enterprise Linux AS release 3 (Taroon Update 6) correctly detected
PASSED: testcases/rhel-3u8: rhel 3 8 Red Hat Enterprise Linux AS release 3 (Taroon Update 8) correctly detected
PASSED: testcases/rhel-4: rhel 4 0 Red Hat Enterprise Linux AS release 4 (Nahant) correctly detected
PASSED: testcases/rhel-4u1: rhel 4 1 Red Hat Enterprise Linux AS release 4 (Nahant Update 1) correctly detected
PASSED: testcases/rhel-4u2: rhel 4 2 Red Hat Enterprise Linux AS release 4 (Nahant Update 2) correctly detected
PASSED: testcases/rhel-4u3: rhel 4 3 Red Hat Enterprise Linux AS release 4 (Nahant Update 3) correctly detected
PASSED: testcases/rhel-4u4: rhel 4 4 Red Hat Enterprise Linux AS release 4 (Nahant Update 4) correctly detected
PASSED: testcases/rhel-4u5: rhel 4 5 Red Hat Enterprise Linux ES release 4 (Nahant Update 5) correctly detected
PASSED: testcases/rhel-4u6: rhel 4 6 Red Hat Enterprise Linux AS release 4 (Nahant Update 6) correctly detected
PASSED: testcases/rhel-5beta: rhel 5 0beta Red Hat Enterprise Linux Server release 4.92 (Tikanga) correctly detected
PASSED: testcases/rhel-5: rhel 5 0 Red Hat Enterprise Linux Server release 5 (Tikanga) correctly detected
PASSED: testcases/rhel-5u1beta: rhel 5 1beta Red Hat Enterprise Linux Server release 5.1 Beta (Tikanga) correctly detected
PASSED: testcases/rhel-5u1: rhel 5 1 Red Hat Enterprise Linux Server release 5.1 (Tikanga) correctly detected
PASSED: testcases/fc3: fedora 3 0 Fedora Core release 3 (Heidelberg) correctly detected
PASSED: testcases/sles-9: sles 9 0 SUSE LINUX Enterprise Server 9 (i586) correctly detected
PASSED: testcases/sles-9sp3: sles 9 3 SUSE LINUX Enterprise Server 9 (i586) correctly detected
PASSED: testcases/sles-10sp2: sles 10 2 SUSE Linux Enterprise Server 10 (i586) correctly detected
PASSED: testcases/sles-11: sles 11 0 SUSE Linux Enterprise Server 11 (i586) correctly detected
PASSED: testcases/ddk-0.5.6-2991c: xe-ddk 0.5.6 2991c Rio DDK release 0.5.6-2991c (xenenterprise) correctly detected
PASSED: testcases/sdk-0.5.6-2991c: xe-sdk 0.5.6 2991c Rio SDK release 0.5.6-2991c (xenenterprise) correctly detected
PASSED: testcases/centos4: centos 4 0 CentOS release 4.0 (Final) correctly detected
PASSED: testcases/centos5: centos 5 0 CentOS release 5 (Final) correctly detected
PASSED: testcases/lsb-ubuntu-6.10: ubuntu 6 10  correctly detected
PASSED: testcases/lsb-ubuntu-7.04: ubuntu 7 04 Ubuntu 7.04 correctly detected
PASSED: testcases/oracle-5: oracle 5 0 Enterprise Linux Enterprise Linux Server release 5 (Carthage) correctly detected
PASSED: testcases/oracle-5u1: oracle 5 1 Enterprise Linux Enterprise Linux Server release 5.1 (Carthage) correctly detected
PASSED: testcases/lsb-coreos-367.1.0: coreos 367 1.0 CoreOS 367.1.0 correctly detected
PASSED: testcases/sle-15: sles 15 0 SUSE Linux Enterprise Server 15 correctly detected
PASSED: testcases/sle-15sp1: sles 15 1 SUSE Linux Enterprise Server 15 SP1 correctly detected
```

And

```
[root@localhost ~]# ./xe-linux-distribution
os_distro="rocky"
os_majorver="8"
os_minorver="3"
os_uname="4.18.0-240.22.1.el8.x86_64"
os_name="Rocky Linux release 8.3"
```

**Comment by stormi** [comment]
I noticed that there are other files that would need the same treatment regarding indentation. I'll push an updated commit.

**Comment by stormi** [comment]
So I have now updated xe-linux-distribution-test and tests still pass.

I have also updated xe-linux-distribution.init and although my change appears trivial to me, I'll check that the service starts correctly on a guest.

**Comment by stormi** [comment]
Looks good on the initscript side:

```
[root@localhost ~]# cp xe-linux-distribution.init /etc/init.d/xe-linux-distribution 
cp : voulez-vous écraser '/etc/init.d/xe-linux-distribution' ? y
[root@localhost ~]# systemctl daemon-reload
[root@localhost ~]# service xe-linux-distribution stop
Stopping xe-linux-distribution (via systemctl):            [  OK  ]
[root@localhost ~]# service xe-linux-distribution start
Starting xe-linux-distribution (via systemctl):            [  OK  ]
[root@localhost ~]# pgrep xe-daemon
64621
```

**Review by xihuan-citrix — APPROVED** [review]

**Review by minli1 — APPROVED** [review]

**Pull request merged**
