### PR TITLE
CA-243280: Report mac for guest VM

### PR DESCRIPTION
**Pull request by cheng-z**
Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>

### CODE REVIEW

**Comment by cheng-z** [comment]
Hi @fillzero and @rdobson 
Could you please help to review the code and let me know if any concern?
Thanks.

**Comment by fillzero** [comment]
This looks good.

**Comment by cheng-z** [comment]
Hi @robertbreker 
Could you please help to review the code and let me know if any comments?

**Comment by cheng-z** [comment]
Hi @fillzero 
Please help to merge the code if no comments.
Thanks.

**Pull request merged**
