### PR TITLE
CA-172369: Golang Guest Agent doesn't use print the logs into guest machine syslog

### PR DESCRIPTION
**Pull request by phusl**
1. Add syslog writer
2. Use ioutil.WriteFile to write pid
3. Refine logger.Printf usage

Signed-off-by: Phus Lu <phus.lu@citrix.com>

### CODE REVIEW

**Comment by rdobson** [comment]
Hi @phusl, was there a reason to avoid using the native syslog golang library? (to avoid having to call out to a CLI):
https://golang.org/pkg/log/syslog/

If cross compilation is an issue, then this wrapper might be helpful?
https://github.com/hashicorp/go-syslog

**Comment by phusl** [comment]
Hi @rdobson, thank you!

In the past, xenserver(6.0+) only release i386 guest-utilities version. It means that, if we follow this rule, we should make sure the golang-i386 guest-utilities could run on x86_64 linux.

In my practise, if we import `syslog` or `net` packages, then the built out i386 version guest-utilities cannot start up on x86_64 linux. (e.g. CentOS 7). Unless glibc.i386 was installed.

And hashicorp/go-syslog also has this problem.

To workaround this issue, we have to call out to a CLI. :(

**Comment by Zhengchai** [comment]
HI @rdobson  - do you think is this OK for us to merge this CA ticket fix now?

**Comment by rdobson** [comment]
(Sorry @Zhengchai  - I missed this comment!).

**Comment by Zhengchai** [comment]
@rdobson no worries, we are not merge to trunk yet -- please raise comments if we have please.thanks :-).

**Comment by rdobson** [comment]
No issues on my side - @phusl 's comments make sense. At some point in the future we might decide to release multiple packages - particularly when considering distributing this via a distros packaging mechanism.

**Comment by Zhengchai** [comment]
thanks -- that is a good point. keep in-mind.

**Pull request merged**
